We don't want the real AWS Lambda function executed in our tests.

Thus, create a bean to provide an implementation of `VatValidator` in the test phase:

[source,groovy]
.invoice/src/test/groovy/example/micronaut/VatValidatorMock.groovy
----
include::{sourceDir}/invoice/src/test/groovy/example/micronaut/VatValidatorMock.groovy[]
----

Create a JUnit test which verifies the logic:

[source,groovy]
.invoice/src/test/groovy/example/micronaut/InvoiceControllerSpec.groovy
----
include::{sourceDir}/invoice/src/test/groovy/example/micronaut/InvoiceControllerSpec.groovy[]
----

<1> To run the application from a unit test you can use the http://docs.micronaut.io/snapshot/api/io/micronaut/runtime/server/EmbeddedServer.html[EmbeddedServer] interface.
<2> Register a `RxHttpClient` bean in the application context and point it to the embedded server URL. The `EmbeddedServer` interface provides the URL of the server under test which runs on a random port.
<3> Verify the bean for interface `VatValidator` is `VatValidatorMock`.

If you are curious about how the 11.55 is calculated.
Given a 21% VAT.

|===
| Price | Count | Line VAT
| 19,99 | 2 | 8,3958
| 15 | 1 | 3,15
| | Total VAT | 11,55
| ===

include::{commondir}/common-testApp.adoc[]
